[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "1a24157d6f675322e00f912cbc9828865a74c5c4"
mpi = "mpiabi"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "facaf6a9478f40fcce835b3f07207d94644d501ce9b783d515c5df4b4db4add3"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.aarch64-apple-darwin-mpi+mpiabi.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "5a78168d9dac43b06d01b210906211258a8fd1af"
mpi = "mpich"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "6323143c7896978937805c3eca64118c5ef5fe7fa72a5d314e94550f66f38a9f"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "e2aeb4c139975777077d8db38fc207822fc3f347"
mpi = "mpitrampoline"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "2a366db94a3837bb8c8b50b19e8d55bca17b5d56d7b0ca9486256c5641b08679"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "8c417915971937325daf77edc8de4ff3c9e59cd3"
mpi = "openmpi"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "a62bc02d09ee95c78d2b907b573bf95a5e838d307aff99538bd3e611ddedcfe1"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a67ba19906a780d5e5924efbfcf9105a7134c7f"
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "b4bc5810e801a54f64f05c1f97d619ffe688cb904e1f5ad1e961bd0c1d55f4cb"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.aarch64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60f57a619a07dc43070523b0226810d61beb58e1"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "0f9ab937b23a581cd8743a779e55cea4c502b74751a460d554951231f513dae8"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1044b4ac04a099e8b2c1ce16f9e3f0fb18aaf995"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "4bdd91c3d5095fc185bcc42fe9383c240834c1218ea1859346de974754838c43"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e223028abb4b7da1848c1f94cb2e4c64670953e7"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "d57381111055d47aa5327934557a88cc201b5b8e851b37249540b1a23684c8e6"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8f325ef32a9ecd2d2b0bc1fde3b41d30b0d15ee"
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "ba5abbb3c1ad7267c6ee513c8066a049be9c4fe9b5f8e91a8eed9d135d27e27f"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.aarch64-linux-musl-cxx11-mpi+mpiabi.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82a44c0223eb733f9a3d55cb50530bf1cc9410be"
libc = "musl"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "b64087037acd422aa06016c1a595ce88f10a430e64f965e056136bdd129b38b0"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.aarch64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fcb84544a1fcb376d0d9aa5efb38506f6200bf4"
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "e0c0f98a6bba2018493d327f18d69a03eba80fef6f6e24966db74b47bed8530a"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.aarch64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "d61939002efe846ab1cdae0205c25a811997e6b5"
mpi = "mpiabi"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "0151e9f9f3e1c5dba99a4eaba6cdfa8baa880a78a874cba134285a86b34b5f0b"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.aarch64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "3ec25ea90e4281f51a79b6b50bdfa318ed23ea6b"
mpi = "mpich"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "3b00a179ece92ddc4b00af92b787add488fb65409a5eea76b9eece0d9f34f978"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.aarch64-unknown-freebsd-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "bb4aafe9386df2e5d3a0cbfd61d71d10ff6e9134"
mpi = "mpitrampoline"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "ed6192d5eda917ed0e02d276e5372d2a74e3e5b9640e3b75a73fb096f0154010"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.aarch64-unknown-freebsd-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "aarch64"
git-tree-sha1 = "6e5c15e2f397b68c0967003681acb204471ac0d3"
mpi = "openmpi"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "c120295086afde2fbe43003591f873fb6629edf17da21423faffb3692a2bb04f"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.aarch64-unknown-freebsd-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3007b33ca7c6e9df98237decad3b6206e4068b14"
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "b50f55d51db92e3e3105af93d7150b159b1fefdf3bf913b3b0b91324a949cfd2"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.powerpc64le-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[ADIOS2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12452fe484a44a144fb94a535703ca2e01ef9900"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "5723ad707c11ca35ab52a23e08b8892aa73c1495386ff92a44c525582fc62daa"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01628ae846e12896b4c986188cdcb8f048c60505"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "8fb934a795542137547682fbb8717ef5759ef7ad3f5bc6aceaeb5a3229238c27"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.powerpc64le-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83aa88c9c12511830c4a5f094d0a0a29f689ec71"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "4ad45ad28357adb12594b41a02d02c2b31fc87155c2b4dab5c1a0763915f2b94"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09c1959d389e88521deebfe0222d781a21013809"
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "b06185234ea73b2ea4b4e515c79f1c960be083cf9a20dd85fb41063c4a2f2149"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.riscv64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[ADIOS2]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9a810396557049727bfaf51ad95e7033bcd4dca"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "f1dd43332497e773e5b5b4a32b5a5906c7d2e037c1894abda18ad9dbd9f5da18"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.riscv64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f0a9ed74811f340081d470131c1ae4b490aaa59"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "bc07207cd570e2326889b115a2733289ab0d382402e695ec2f7748550237fe57"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.riscv64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd2c2b2f44b1d736f306ed777a98399e9cee28c5"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "2d82808be13b1fefd9feac1aa291224aefdd16a722e89ca06072a59a9a98c353"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.riscv64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "23ed1775a5eb38b4b4522569de1be105168e0bca"
mpi = "mpiabi"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "fb2f5bf651a9ec102a2cc37d26384fb7181620b7b3aa19698a7a3062a40bb4b0"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.x86_64-apple-darwin-mpi+mpiabi.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "e7709f0b156c0eaabbc2106e47c1f5e765e97fe6"
mpi = "mpich"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "3e09bde4ac6e4fb5769bab3c5f91361b5964bf182187c05858d3e258bd05b744"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "03a03fe7b28ffed3971426c61bb0e56f67c0b2c1"
mpi = "mpitrampoline"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "b4b4ce7b7e1f970d01a863abd187e54792ef680fa6a9d4842625e1e3125a7acb"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "bf931a79934a48a2d78237687f3cd012b60abdf5"
mpi = "openmpi"
os = "macos"

    [[ADIOS2.download]]
    sha256 = "4499d99f3318e18e399a71284747f8ca7e4683a73e1f8aa355d5a7fb05f15569"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "129bd6dcf6fe60a1cef7d20153b6950481a0040d"
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "0e3d92386a59087cb160ff5854eb0d276b9e092cfdc0cd47b5665dae551f3411"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.x86_64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f9be260ce6e7ecf2a9e5390397feaae94effc45"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "93951f48d03229e165f646ad9e43b53cc745594cf6f07abf622c9b72690e4d61"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d2157123a40a42451fd7ecab05a645a2932840b"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "4194444df96330c59d9aa3664267108ec966b80d8f48bfc53898502df3b0ac4d"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "584926f4acc869234fefc5bfa48020276c4d9422"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "f69e193f4eb639848ffd4d8ec40ddb8adafb2b68a97c89cbe7dcca16da387dd1"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b323eba71a22ae9b6227f54a552dd9d9df899d8b"
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "d86552bd26530eadacf8297358f65921cc96a5b72e04f4aa55a497f42a274df5"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.x86_64-linux-musl-cxx11-mpi+mpiabi.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72f6483952b31eab8070650b31ab16537fff66db"
libc = "musl"
mpi = "mpich"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "f5eb259a1a4916e00a572561d6d4c9e48f18d95f1c6ebf453c443daa4b362ac0"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.x86_64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ddeb1a878f34714150b82360eed33bfce59d1f4"
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[ADIOS2.download]]
    sha256 = "6b19430ffead078f8148dd90c43a791e85f2e9eab2fd71d811d06bb48319bce9"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.x86_64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "325996391a1d7c207e49e568d6fbd9326ba617e7"
mpi = "mpiabi"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "cdd005c8c5c457bf868d66fab6ed204e53770816edb2a4f2aeb1f7c17485789d"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.x86_64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "5f2d463ede810de9fd70526e7ed831572818ba07"
mpi = "mpich"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "5e9c1cc4325374f47db71f52ac4db9b6f73cc593d62a5e36fb7b48be20373364"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "475e060542358823f84ac8d3423fb4b9c51d90f1"
mpi = "mpitrampoline"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "90f738b5912f19f1b2de7c9c2b93a6e958b2d79eb4b08d9c7e5aa3d8e2647c35"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.x86_64-unknown-freebsd-mpi+mpitrampoline.tar.gz"
[[ADIOS2]]
arch = "x86_64"
git-tree-sha1 = "b1de791b55b4b1136f115a96787682ccf949ad7d"
mpi = "openmpi"
os = "freebsd"

    [[ADIOS2.download]]
    sha256 = "899e0b97081fcf6577e04a1441ff66e875cc0780d2616f5fb8e5fd0eb0585d53"
    url = "https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/releases/download/ADIOS2-v201.1100.3+0/ADIOS2.v201.1100.3.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
