# Autogenerated wrapper script for ADIOS2_jll for riscv64-linux-gnu-cxx11-mpi+openmpi
export bpls, libadios2_c, libadios2_c_mpi, libadios2_core, libadios2_core_mpi, libadios2_cxx, libadios2_cxx_mpi

using Blosc2_jll
using Bzip2_jll
using CompilerSupportLibraries_jll
using HDF5_jll
using Libffi_jll
using MGARD_jll
using ZeroMQ_jll
using Zstd_jll
using libpng_jll
using protoc_jll
using pugixml_jll
using yaml_cpp_jll
using zfp_jll
using OpenMPI_jll
JLLWrappers.@generate_wrapper_header("ADIOS2")
JLLWrappers.@declare_library_product(libadios2_c, "libadios2_c.so.2.11")
JLLWrappers.@declare_library_product(libadios2_c_mpi, "libadios2_c_mpi.so.2.11")
JLLWrappers.@declare_library_product(libadios2_core, "libadios2_core.so.2.11")
JLLWrappers.@declare_library_product(libadios2_core_mpi, "libadios2_core_mpi.so.2.11")
JLLWrappers.@declare_library_product(libadios2_cxx, "libadios2_cxx.so.2.11")
JLLWrappers.@declare_library_product(libadios2_cxx_mpi, "libadios2_cxx_mpi.so.2.11")
JLLWrappers.@declare_executable_product(bpls)
function __init__()
    JLLWrappers.@generate_init_header(Blosc2_jll, Bzip2_jll, CompilerSupportLibraries_jll, HDF5_jll, Libffi_jll, MGARD_jll, ZeroMQ_jll, Zstd_jll, libpng_jll, protoc_jll, pugixml_jll, yaml_cpp_jll, zfp_jll, OpenMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libadios2_c,
        "lib/libadios2_c.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libadios2_c_mpi,
        "lib/libadios2_c_mpi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libadios2_core,
        "lib/libadios2_core.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libadios2_core_mpi,
        "lib/libadios2_core_mpi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libadios2_cxx,
        "lib/libadios2_cxx.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libadios2_cxx_mpi,
        "lib/libadios2_cxx_mpi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        bpls,
        "bin/bpls",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
